spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - http://localhost:*
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
            allowCredentials: true


server:
  port: 9000
jwt:
  secret: justexpandingmyknowledgeinmicroserviesothaticanusemyknowledgetoachievethesomethingbig

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
