spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - http://localhost:*
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
            allowCredentials: true


server:
  port: 9000
jwt:
  secret: justexpandingmyknowledgeinmicroserviesothaticanusemyknowledgetoachievethesomethingbig

services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8082}

  match-service:
    url: ${MATCH_SERVICE_URL:http://localhost:8083}

  chat-service:
    url: ${CHAT_SERVICE_URL:http://localhost:8085}
    websocket-url: ${CHAT_WEBSOCKET_URL:ws://localhost:8085}
