spring:
  application:
    name: chatService

  datasource:
    url: jdbc:postgresql://ep-bitter-dream-b4m5bb2b-pooler.c-6.us-east-2.aws.neon.tech/tinder?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_BDlqShZ6RzU8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8085}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never